package com.scloud.discoveryeureka.entity;

import java.io.Serializable;

public class RoutInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SMD_ROUTEINFO.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SMD_ROUTEINFO.SFZH
     *
     * @mbg.generated
     */
    private String sfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SMD_ROUTEINFO.RETURN_TIME
     *
     * @mbg.generated
     */
    private String returnTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SMD_ROUTEINFO.SFTJYQ
     *
     * @mbg.generated
     */
    private String sftjyq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SMD_ROUTEINFO.DISTANCE_INSTRUC
     *
     * @mbg.generated
     */
    private String distanceInstruc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SMD_ROUTEINFO.SFJCYQRY
     *
     * @mbg.generated
     */
    private String sfjcyqry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SMD_ROUTEINFO.SYMPT_INSTRUC
     *
     * @mbg.generated
     */
    private String symptInstruc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SMD_ROUTEINFO.SFXQYQ
     *
     * @mbg.generated
     */
    private String sfxqyq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SMD_ROUTEINFO.YJXXDG
     *
     * @mbg.generated
     */
    private String yjxxdg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SMD_ROUTEINFO.TRAFFIC_WAY
     *
     * @mbg.generated
     */
    private String trafficWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SMD_ROUTEINFO.ADDUSER
     *
     * @mbg.generated
     */
    private String adduser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SMD_ROUTEINFO.ADDTIME
     *
     * @mbg.generated
     */
    private String addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SMD_ROUTEINFO.UPDATEUSER
     *
     * @mbg.generated
     */
    private String updateuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SMD_ROUTEINFO.UPDATETIME
     *
     * @mbg.generated
     */
    private String updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SMD_ROUTEINFO.DELETE_STATUS
     *
     * @mbg.generated
     */
    private String deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SMD_ROUTEINFO.TRAFFICELSE_WAY
     *
     * @mbg.generated
     */
    private String trafficelseWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SMD_ROUTEINFO.GW_STATUS
     *
     * @mbg.generated
     */
    private String gwStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SMD_ROUTEINFO
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SMD_ROUTEINFO.ID
     *
     * @return the value of T_SMD_ROUTEINFO.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SMD_ROUTEINFO.ID
     *
     * @param id the value for T_SMD_ROUTEINFO.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SMD_ROUTEINFO.SFZH
     *
     * @return the value of T_SMD_ROUTEINFO.SFZH
     *
     * @mbg.generated
     */
    public String getSfzh() {
        return sfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SMD_ROUTEINFO.SFZH
     *
     * @param sfzh the value for T_SMD_ROUTEINFO.SFZH
     *
     * @mbg.generated
     */
    public void setSfzh(String sfzh) {
        this.sfzh = sfzh == null ? null : sfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SMD_ROUTEINFO.RETURN_TIME
     *
     * @return the value of T_SMD_ROUTEINFO.RETURN_TIME
     *
     * @mbg.generated
     */
    public String getReturnTime() {
        return returnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SMD_ROUTEINFO.RETURN_TIME
     *
     * @param returnTime the value for T_SMD_ROUTEINFO.RETURN_TIME
     *
     * @mbg.generated
     */
    public void setReturnTime(String returnTime) {
        this.returnTime = returnTime == null ? null : returnTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SMD_ROUTEINFO.SFTJYQ
     *
     * @return the value of T_SMD_ROUTEINFO.SFTJYQ
     *
     * @mbg.generated
     */
    public String getSftjyq() {
        return sftjyq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SMD_ROUTEINFO.SFTJYQ
     *
     * @param sftjyq the value for T_SMD_ROUTEINFO.SFTJYQ
     *
     * @mbg.generated
     */
    public void setSftjyq(String sftjyq) {
        this.sftjyq = sftjyq == null ? null : sftjyq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SMD_ROUTEINFO.DISTANCE_INSTRUC
     *
     * @return the value of T_SMD_ROUTEINFO.DISTANCE_INSTRUC
     *
     * @mbg.generated
     */
    public String getDistanceInstruc() {
        return distanceInstruc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SMD_ROUTEINFO.DISTANCE_INSTRUC
     *
     * @param distanceInstruc the value for T_SMD_ROUTEINFO.DISTANCE_INSTRUC
     *
     * @mbg.generated
     */
    public void setDistanceInstruc(String distanceInstruc) {
        this.distanceInstruc = distanceInstruc == null ? null : distanceInstruc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SMD_ROUTEINFO.SFJCYQRY
     *
     * @return the value of T_SMD_ROUTEINFO.SFJCYQRY
     *
     * @mbg.generated
     */
    public String getSfjcyqry() {
        return sfjcyqry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SMD_ROUTEINFO.SFJCYQRY
     *
     * @param sfjcyqry the value for T_SMD_ROUTEINFO.SFJCYQRY
     *
     * @mbg.generated
     */
    public void setSfjcyqry(String sfjcyqry) {
        this.sfjcyqry = sfjcyqry == null ? null : sfjcyqry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SMD_ROUTEINFO.SYMPT_INSTRUC
     *
     * @return the value of T_SMD_ROUTEINFO.SYMPT_INSTRUC
     *
     * @mbg.generated
     */
    public String getSymptInstruc() {
        return symptInstruc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SMD_ROUTEINFO.SYMPT_INSTRUC
     *
     * @param symptInstruc the value for T_SMD_ROUTEINFO.SYMPT_INSTRUC
     *
     * @mbg.generated
     */
    public void setSymptInstruc(String symptInstruc) {
        this.symptInstruc = symptInstruc == null ? null : symptInstruc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SMD_ROUTEINFO.SFXQYQ
     *
     * @return the value of T_SMD_ROUTEINFO.SFXQYQ
     *
     * @mbg.generated
     */
    public String getSfxqyq() {
        return sfxqyq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SMD_ROUTEINFO.SFXQYQ
     *
     * @param sfxqyq the value for T_SMD_ROUTEINFO.SFXQYQ
     *
     * @mbg.generated
     */
    public void setSfxqyq(String sfxqyq) {
        this.sfxqyq = sfxqyq == null ? null : sfxqyq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SMD_ROUTEINFO.YJXXDG
     *
     * @return the value of T_SMD_ROUTEINFO.YJXXDG
     *
     * @mbg.generated
     */
    public String getYjxxdg() {
        return yjxxdg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SMD_ROUTEINFO.YJXXDG
     *
     * @param yjxxdg the value for T_SMD_ROUTEINFO.YJXXDG
     *
     * @mbg.generated
     */
    public void setYjxxdg(String yjxxdg) {
        this.yjxxdg = yjxxdg == null ? null : yjxxdg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SMD_ROUTEINFO.TRAFFIC_WAY
     *
     * @return the value of T_SMD_ROUTEINFO.TRAFFIC_WAY
     *
     * @mbg.generated
     */
    public String getTrafficWay() {
        return trafficWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SMD_ROUTEINFO.TRAFFIC_WAY
     *
     * @param trafficWay the value for T_SMD_ROUTEINFO.TRAFFIC_WAY
     *
     * @mbg.generated
     */
    public void setTrafficWay(String trafficWay) {
        this.trafficWay = trafficWay == null ? null : trafficWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SMD_ROUTEINFO.ADDUSER
     *
     * @return the value of T_SMD_ROUTEINFO.ADDUSER
     *
     * @mbg.generated
     */
    public String getAdduser() {
        return adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SMD_ROUTEINFO.ADDUSER
     *
     * @param adduser the value for T_SMD_ROUTEINFO.ADDUSER
     *
     * @mbg.generated
     */
    public void setAdduser(String adduser) {
        this.adduser = adduser == null ? null : adduser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SMD_ROUTEINFO.ADDTIME
     *
     * @return the value of T_SMD_ROUTEINFO.ADDTIME
     *
     * @mbg.generated
     */
    public String getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SMD_ROUTEINFO.ADDTIME
     *
     * @param addtime the value for T_SMD_ROUTEINFO.ADDTIME
     *
     * @mbg.generated
     */
    public void setAddtime(String addtime) {
        this.addtime = addtime == null ? null : addtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SMD_ROUTEINFO.UPDATEUSER
     *
     * @return the value of T_SMD_ROUTEINFO.UPDATEUSER
     *
     * @mbg.generated
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SMD_ROUTEINFO.UPDATEUSER
     *
     * @param updateuser the value for T_SMD_ROUTEINFO.UPDATEUSER
     *
     * @mbg.generated
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser == null ? null : updateuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SMD_ROUTEINFO.UPDATETIME
     *
     * @return the value of T_SMD_ROUTEINFO.UPDATETIME
     *
     * @mbg.generated
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SMD_ROUTEINFO.UPDATETIME
     *
     * @param updatetime the value for T_SMD_ROUTEINFO.UPDATETIME
     *
     * @mbg.generated
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SMD_ROUTEINFO.DELETE_STATUS
     *
     * @return the value of T_SMD_ROUTEINFO.DELETE_STATUS
     *
     * @mbg.generated
     */
    public String getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SMD_ROUTEINFO.DELETE_STATUS
     *
     * @param deleteStatus the value for T_SMD_ROUTEINFO.DELETE_STATUS
     *
     * @mbg.generated
     */
    public void setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus == null ? null : deleteStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SMD_ROUTEINFO.TRAFFICELSE_WAY
     *
     * @return the value of T_SMD_ROUTEINFO.TRAFFICELSE_WAY
     *
     * @mbg.generated
     */
    public String getTrafficelseWay() {
        return trafficelseWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SMD_ROUTEINFO.TRAFFICELSE_WAY
     *
     * @param trafficelseWay the value for T_SMD_ROUTEINFO.TRAFFICELSE_WAY
     *
     * @mbg.generated
     */
    public void setTrafficelseWay(String trafficelseWay) {
        this.trafficelseWay = trafficelseWay == null ? null : trafficelseWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SMD_ROUTEINFO.GW_STATUS
     *
     * @return the value of T_SMD_ROUTEINFO.GW_STATUS
     *
     * @mbg.generated
     */
    public String getGwStatus() {
        return gwStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SMD_ROUTEINFO.GW_STATUS
     *
     * @param gwStatus the value for T_SMD_ROUTEINFO.GW_STATUS
     *
     * @mbg.generated
     */
    public void setGwStatus(String gwStatus) {
        this.gwStatus = gwStatus == null ? null : gwStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SMD_ROUTEINFO
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", sfzh=").append(sfzh);
        sb.append(", returnTime=").append(returnTime);
        sb.append(", sftjyq=").append(sftjyq);
        sb.append(", distanceInstruc=").append(distanceInstruc);
        sb.append(", sfjcyqry=").append(sfjcyqry);
        sb.append(", symptInstruc=").append(symptInstruc);
        sb.append(", sfxqyq=").append(sfxqyq);
        sb.append(", yjxxdg=").append(yjxxdg);
        sb.append(", trafficWay=").append(trafficWay);
        sb.append(", adduser=").append(adduser);
        sb.append(", addtime=").append(addtime);
        sb.append(", updateuser=").append(updateuser);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", deleteStatus=").append(deleteStatus);
        sb.append(", trafficelseWay=").append(trafficelseWay);
        sb.append(", gwStatus=").append(gwStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}